/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.gekalogiros.kafka;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class KafkaMessage extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -8785519497703919060L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"KafkaMessage\",\"namespace\":\"com.gekalogiros.kafka\",\"fields\":[{\"name\":\"body\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<KafkaMessage> ENCODER =
      new BinaryMessageEncoder<KafkaMessage>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<KafkaMessage> DECODER =
      new BinaryMessageDecoder<KafkaMessage>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<KafkaMessage> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<KafkaMessage> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<KafkaMessage>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this KafkaMessage to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a KafkaMessage from a ByteBuffer. */
  public static KafkaMessage fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence body;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public KafkaMessage() {}

  /**
   * All-args constructor.
   * @param body The new value for body
   */
  public KafkaMessage(java.lang.CharSequence body) {
    this.body = body;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return body;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: body = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'body' field.
   * @return The value of the 'body' field.
   */
  public java.lang.CharSequence getBody() {
    return body;
  }

  /**
   * Sets the value of the 'body' field.
   * @param value the value to set.
   */
  public void setBody(java.lang.CharSequence value) {
    this.body = value;
  }

  /**
   * Creates a new KafkaMessage RecordBuilder.
   * @return A new KafkaMessage RecordBuilder
   */
  public static com.gekalogiros.kafka.KafkaMessage.Builder newBuilder() {
    return new com.gekalogiros.kafka.KafkaMessage.Builder();
  }

  /**
   * Creates a new KafkaMessage RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new KafkaMessage RecordBuilder
   */
  public static com.gekalogiros.kafka.KafkaMessage.Builder newBuilder(com.gekalogiros.kafka.KafkaMessage.Builder other) {
    return new com.gekalogiros.kafka.KafkaMessage.Builder(other);
  }

  /**
   * Creates a new KafkaMessage RecordBuilder by copying an existing KafkaMessage instance.
   * @param other The existing instance to copy.
   * @return A new KafkaMessage RecordBuilder
   */
  public static com.gekalogiros.kafka.KafkaMessage.Builder newBuilder(com.gekalogiros.kafka.KafkaMessage other) {
    return new com.gekalogiros.kafka.KafkaMessage.Builder(other);
  }

  /**
   * RecordBuilder for KafkaMessage instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<KafkaMessage>
    implements org.apache.avro.data.RecordBuilder<KafkaMessage> {

    private java.lang.CharSequence body;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.gekalogiros.kafka.KafkaMessage.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.body)) {
        this.body = data().deepCopy(fields()[0].schema(), other.body);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing KafkaMessage instance
     * @param other The existing instance to copy.
     */
    private Builder(com.gekalogiros.kafka.KafkaMessage other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.body)) {
        this.body = data().deepCopy(fields()[0].schema(), other.body);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'body' field.
      * @return The value.
      */
    public java.lang.CharSequence getBody() {
      return body;
    }

    /**
      * Sets the value of the 'body' field.
      * @param value The value of 'body'.
      * @return This builder.
      */
    public com.gekalogiros.kafka.KafkaMessage.Builder setBody(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.body = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'body' field has been set.
      * @return True if the 'body' field has been set, false otherwise.
      */
    public boolean hasBody() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'body' field.
      * @return This builder.
      */
    public com.gekalogiros.kafka.KafkaMessage.Builder clearBody() {
      body = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public KafkaMessage build() {
      try {
        KafkaMessage record = new KafkaMessage();
        record.body = fieldSetFlags()[0] ? this.body : (java.lang.CharSequence) defaultValue(fields()[0]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<KafkaMessage>
    WRITER$ = (org.apache.avro.io.DatumWriter<KafkaMessage>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<KafkaMessage>
    READER$ = (org.apache.avro.io.DatumReader<KafkaMessage>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
